export default function Projects() {
    return (<section className="empty-set__skeleton py-32" data-depth="-1"><div className="container" data-depth="-1"><h1 className="text-7xl leading-tight uppercase" data-depth="-1"><span className="empty-set__text" data-depth="3">########</span></h1><div className="mt-10 grid grid-cols-1 gap-6 md:grid-cols-2" data-depth="-1"><div className="group overflow-hidden rounded-lg border border-border bg-background" style={{
            opacity: "0",
            transform: "translateY(50px)"
          }} data-depth="3"><a className="block overflow-hidden" data-depth="4"><img className="h-96 w-full object-cover transition-transform duration-500 ease-in-out group-hover:scale-105" data-depth="5"></img></a><div className="flex items-center justify-between px-5 py-4" data-depth="-1"><div data-depth="-1"><h2 className="text-lg font-semibold" data-depth="-1"><span className="empty-set__text" data-depth="7">###### ######## ########</span></h2><p className="text-muted-foreground" data-depth="-1"><span className="empty-set__text" data-depth="7">############</span></p></div><div className="rounded-2xl border border-border px-5 py-2 text-sm font-semibold" data-depth="5"><span className="empty-set__text" data-depth="6">####</span></div></div></div><div className="group overflow-hidden rounded-lg border border-border bg-background" style={{
            opacity: "0",
            transform: "translateY(50px)"
          }} data-depth="3"><a className="block overflow-hidden" data-depth="4"><img className="h-96 w-full object-cover transition-transform duration-500 ease-in-out group-hover:scale-105" data-depth="5"></img></a><div className="flex items-center justify-between px-5 py-4" data-depth="-1"><div data-depth="-1"><h2 className="text-lg font-semibold" data-depth="-1"><span className="empty-set__text" data-depth="7">######## ##### ######</span></h2><p className="text-muted-foreground" data-depth="-1"><span className="empty-set__text" data-depth="7">##### ######</span></p></div><div className="rounded-2xl border border-border px-5 py-2 text-sm font-semibold" data-depth="5"><span className="empty-set__text" data-depth="6">####</span></div></div></div><div className="group overflow-hidden rounded-lg border border-border bg-background" style={{
            opacity: "0",
            transform: "translateY(50px)"
          }} data-depth="3"><a className="block overflow-hidden" data-depth="4"><img className="h-96 w-full object-cover transition-transform duration-500 ease-in-out group-hover:scale-105" data-depth="5"></img></a><div className="flex items-center justify-between px-5 py-4" data-depth="-1"><div data-depth="-1"><h2 className="text-lg font-semibold" data-depth="-1"><span className="empty-set__text" data-depth="7">########## #### #######</span></h2><p className="text-muted-foreground" data-depth="-1"><span className="empty-set__text" data-depth="7">########</span></p></div><div className="rounded-2xl border border-border px-5 py-2 text-sm font-semibold" data-depth="5"><span className="empty-set__text" data-depth="6">####</span></div></div></div><div className="group overflow-hidden rounded-lg border border-border bg-background" style={{
            opacity: "0",
            transform: "translateY(50px)"
          }} data-depth="3"><a className="block overflow-hidden" data-depth="4"><img className="h-96 w-full object-cover transition-transform duration-500 ease-in-out group-hover:scale-105" data-depth="5"></img></a><div className="flex items-center justify-between px-5 py-4" data-depth="-1"><div data-depth="-1"><h2 className="text-lg font-semibold" data-depth="-1"><span className="empty-set__text" data-depth="7">##### ######## #####</span></h2><p className="text-muted-foreground" data-depth="-1"><span className="empty-set__text" data-depth="7">####### ######</span></p></div><div className="rounded-2xl border border-border px-5 py-2 text-sm font-semibold" data-depth="5"><span className="empty-set__text" data-depth="6">####</span></div></div></div><div className="group overflow-hidden rounded-lg border border-border bg-background" style={{
            opacity: "0",
            transform: "translateY(50px)"
          }} data-depth="3"><a className="block overflow-hidden" data-depth="4"><img className="h-96 w-full object-cover transition-transform duration-500 ease-in-out group-hover:scale-105" data-depth="5"></img></a><div className="flex items-center justify-between px-5 py-4" data-depth="-1"><div data-depth="-1"><h2 className="text-lg font-semibold" data-depth="-1"><span className="empty-set__text" data-depth="7">###### ######## ###</span></h2><p className="text-muted-foreground" data-depth="-1"><span className="empty-set__text" data-depth="7">###########</span></p></div><div className="rounded-2xl border border-border px-5 py-2 text-sm font-semibold" data-depth="5"><span className="empty-set__text" data-depth="6">####</span></div></div></div><div className="group overflow-hidden rounded-lg border border-border bg-background" style={{
            opacity: "0",
            transform: "translateY(50px)"
          }} data-depth="3"><a className="block overflow-hidden" data-depth="4"><img className="h-96 w-full object-cover transition-transform duration-500 ease-in-out group-hover:scale-105" data-depth="5"></img></a><div className="flex items-center justify-between px-5 py-4" data-depth="-1"><div data-depth="-1"><h2 className="text-lg font-semibold" data-depth="-1"><span className="empty-set__text" data-depth="7">########## ## ######</span></h2><p className="text-muted-foreground" data-depth="-1"><span className="empty-set__text" data-depth="7">########### ######</span></p></div><div className="rounded-2xl border border-border px-5 py-2 text-sm font-semibold" data-depth="5"><span className="empty-set__text" data-depth="6">####</span></div></div></div></div></div></section>);
}
