session_name: skullmaster
start_directory: ./

windows:
  - window_name: dev_servers
    layout: tiled
    panes:
      - pnpm run dev
      - cd apps/demo && pnpm skullmaster serve
      - lazygit
      - opencode .

  - window_name: editor
    focus: true
    panes:
      - nvim .
