/* eslint-disable */
/* oxlint-disable */
/* biome-ignore-all lint */
/* @ts-nocheck */

/**
 * Auto-generated by Skullmaster.
 *
 * Do not edit this file manually.
 * Use Skullmaster commands to add, update, or remove skeletons.
 *
 * To remove unused skeletons:
 *   pnpm skeleton prune
 */

import DefaultBone from "./DefaultBone"
import { lazy } from "react"

const registry: Record<string, any> = {
    Projects: lazy(() => import("./bones/Projects")),
    Pricing: lazy(() => import("./bones/Pricing")),
    Contact7: lazy(() => import("./bones/Contact7")),
    Testimonial10: lazy(() => import("./bones/Testimonial10")),
    Download2: lazy(() => import("./bones/Download2")),
    Team1: lazy(() => import("./bones/Team1")),
    BookADemo1: lazy(() => import("./bones/BookADemo1")),
}

type SkeletonProps = {
    name: string
}

export default function Skeleton({ name }: SkeletonProps) {
    const Component = registry[name]

    if (!Component) {
        return <DefaultBone />
    }

    return <Component />
}
