/* eslint-disable */
/* oxlint-disable */
/* biome-ignore-all lint */
/* @ts-nocheck */

/**
 * Auto-generated by Skullmaster.
 *
 * Do not edit this file manually.
 * Use Skullmaster commands to add, update, or remove skeletons.
 *
 * To remove unused skeletons:
 *   pnpm skeleton prune
 */

import DefaultBone from "./DefaultBone";
import { lazy } from "react";

const registry = {
  DefaultBone: lazy(() => import("./DefaultBone")),
};

export default function Skeleton({ name }) {
  const Component = registry[name];

  if (!Component) {
    return <DefaultBone />;
  }

  return <Component />;
}
