import { writeFile } from "node:fs/promises";

export default async function defaultBone(target: string) {
  await writeFile(
    target,
    `
/* eslint-disable */
/* oxlint-disable */
/* biome-ignore-all lint */
/* @ts-nocheck */

import type { HTMLProps } from "react";

/**
 * Auto-generated by Skullmaster.
 *
 * This is the default fallback skeleton component displayed when a
 * matching skeleton implementation cannot be found in the registry.
 *
 * You may freely customize or replace this component to match the
 * loading experience of your application.
 */
type DefaultBoneProps = HTMLProps<HTMLDivElement>;

export default function DefaultBone(props: DefaultBoneProps) {
  return <div {...props}>loading...</div>;
}
`,
    "utf8",
  );
}
