import { writeFile } from "node:fs/promises";

export default async function defaultBone(outDir: string, projectType: string) {
  const isTs = projectType.endsWith("ts");

  await writeFile(
    `${outDir}/DefaultBone.${isTs ? "tsx" : "jsx"}`,
    `/* eslint-disable */
/* oxlint-disable */
/* biome-ignore-all lint */
/* @ts-nocheck */

/**
 * Auto-generated by Skullmaster.
 *
 * This is the default fallback skeleton component displayed when a
 * matching skeleton implementation cannot be found in the registry.
 *
 * You may freely customize or replace this component to match the
 * loading experience of your application.
 */
export default function DefaultBone() {
  return <div>loading...</div>;
}
`,
    "utf8",
  );
}
