import { Project, SyntaxKind } from "ts-morph";
import { writeFile } from "node:fs/promises";
import { ensureLazyImport } from "./ensure-lazy-imports";
import { toPascalCase } from "../utils/to-pascal-case";

export async function generateInitialRegistry(outDir: string, projectType: string) {
  const isTs = projectType.endsWith("ts");

  const ext = isTs ? "tsx" : "jsx";

  const skullTypes = isTs
    ? `
export type SkullTweaks = {
  /** Exclude this element and its entire subtree from skeleton generation. */
  hideSubTree?: boolean;
  /** Render this element as transparent (layout preserved) in the skeleton. */
  isTransparent?: boolean;
};

export type WithDataSkull = HTMLAttributes<HTMLElement> & {
  "data-skullmaster": string;
  "data-skip-skull"?: boolean;
  "data-depth"?: "-1";
};
`
    : "";

  const skullUtils = `
const buildSkullAttributes = ({ hideSubTree, isTransparent }${
    isTs ? ": SkullTweaks" : ""
  })${isTs ? ': Omit<WithDataSkull, "data-skullmaster">' : ""} => {
  return {
    "data-skip-skull": hideSubTree,
    "data-depth": isTransparent ? "-1" : undefined,
  };
};

export const markAsSkull = (name: string, tweaks${
    isTs ? ": SkullTweaks" : ""
  } = {})${isTs ? ": WithDataSkull" : ""} => {
  return {
    "data-skullmaster": name,
    ...buildSkullAttributes(tweaks),
  };
};

export const tweakForSkull = (tweaks${
    isTs ? ": SkullTweaks" : ""
  } = {})${isTs ? ': Omit<WithDataSkull, "data-skullmaster">' : ""} => {
  return buildSkullAttributes(tweaks);
};
`;

  const skeletonPropsType = isTs
    ? `
type SkeletonProps = {
  name: keyof typeof registry | (string & {});
  defaultBoneProps?: ComponentProps<typeof DefaultBone>;
};
`
    : "";

  await writeFile(
    `${outDir}/registry.${ext}`,
    `
/* eslint-disable */
/* oxlint-disable */
/* biome-ignore-all lint */
/* @ts-nocheck */

/**
 * Auto-generated by Skullmaster.
 *
 * Do not edit this file manually.
 * Use Skullmaster commands to add, update, or remove skeletons.
 *
 */

import "@skullmaster/react/style.css";
import DefaultBone from "./skeletons/DefaultBone";
${isTs ? 'import { type ComponentProps, type HTMLAttributes } from "react";' : ""}

const registry = {}${isTs ? " as const" : ""};

${skullTypes}${skeletonPropsType}${skullUtils}
export default function Skeleton({
  name,
  defaultBoneProps = {},
}${isTs ? ": SkeletonProps" : ""}) {
  const Component = registry[name];

  if (!Component) {
    return <DefaultBone {...defaultBoneProps} />;
  }

  return <Component />;
}
`,
    "utf8",
  );
}
export type RegistryOperation =
  | { type: "init"; components: string[] }
  | { type: "add"; components: string[] };

export async function generateRegistry(
  operation: RegistryOperation,
  isTs: boolean,
  registryPath: string,
) {
  const project = isTs
    ? new Project({
        tsConfigFilePath: "tsconfig.json",
      })
    : new Project();

  const sourceFile = project.addSourceFileAtPath(registryPath);

  ensureLazyImport(sourceFile);

  const registry =
    sourceFile
      .getVariableDeclaration("registry")
      ?.getInitializerIfKind(SyntaxKind.AsExpression)
      ?.getExpressionIfKind(SyntaxKind.ObjectLiteralExpression) ??
    sourceFile
      .getVariableDeclaration("registry")
      ?.getInitializerIfKind(SyntaxKind.ObjectLiteralExpression);

  if (!registry) {
    throw new Error("Unable to locate registry object, have you ran skullmaster init??");
  }

  const existingComponents = new Set(
    registry
      .getProperties()
      .filter((property) => property.getKind() === SyntaxKind.PropertyAssignment)
      .map((property) => property.asKindOrThrow(SyntaxKind.PropertyAssignment))
      .map((property) => property.getName().replace(/['"]/g, "")),
  );

  for (let component of operation.components) {
    component = toPascalCase(component);

    if (existingComponents.has(component)) {
      continue;
    }

    registry.addPropertyAssignment({
      name: `"${component}"`,
      initializer: `lazy(() => import("./skeletons/${component}"))`,
    });
  }

  if (isTs) {
    const declaration = sourceFile.getVariableDeclarationOrThrow("registry");

    const initializer = declaration.getInitializer();

    if (initializer && !initializer.isKind(SyntaxKind.AsExpression)) {
      declaration.setInitializer(`${initializer.getText()} as const`);
    }
  }

  sourceFile.formatText();

  await sourceFile.save();

  project.saveSync();
}
