import { Project, SyntaxKind } from "ts-morph";
import { writeFile } from "node:fs/promises";
import { ensureLazyImport } from "./ensure-lazy-imports";

export async function generateInitialRegistry(outDir: string, projectType: string) {
  const isTs = projectType.endsWith("ts");

  const ext = isTs ? "tsx" : "jsx";

  const skeletonPropsType = isTs
    ? `
type SkeletonProps = {
  name: string;
};
`
    : "";

  await writeFile(
    `${outDir}/registry.${ext}`,
    `
/* eslint-disable */
/* oxlint-disable */
/* biome-ignore-all lint */
/* @ts-nocheck */

 /**
 * Auto-generated by Skullmaster.
 *
 * Do not edit this file manually.
 * Use Skullmaster commands to add, update, or remove skeletons.
 *
 * To remove unused skeletons:
 *   pnpm skeleton prune
 */


import DefaultBone from "./skeletons/DefaultBone";

const registry${isTs ? ": Record<string, any>" : ""} = {};

${skeletonPropsType}

export default function Skeleton({
  name,
}${isTs ? ": SkeletonProps" : ""}) {
  const Component = registry[name];

  if (!Component) {
    return <DefaultBone />;
  }

  return <Component />;
}
`,
    "utf8",
  );
}

export type RegistryOperation =
  | { type: "init"; components: string[] }
  | { type: "add"; components: string[] };

export async function generateRegistry(
  operation: RegistryOperation,
  isTs: boolean,
  registryPath: string,
) {
  let project: Project;
  if (isTs) {
    project = new Project({
      tsConfigFilePath: "tsconfig.json",
    });
  } else {
    project = new Project();
  }

  const sourceFile = project.addSourceFileAtPath(registryPath);

  ensureLazyImport(sourceFile);

  const registry = sourceFile
    .getVariableDeclaration("registry")
    ?.getInitializerIfKind(SyntaxKind.ObjectLiteralExpression);

  if (!registry) {
    throw new Error("Unable to locate registry object, have you ran skullmaster init??");
  }

  const existingComponents = new Set(
    registry
      .getProperties()
      .filter((property) => property.getKind() === SyntaxKind.PropertyAssignment)
      .map((property) => property.asKindOrThrow(SyntaxKind.PropertyAssignment))
      .map((property) => property.getName().replace(/['"]/g, "")),
  );

  for (const component of operation.components) {
    if (existingComponents.has(component)) {
      continue;
    }

    registry.addPropertyAssignment({
      name: `"${component}"`,
      initializer: `lazy(() => import("./skeletons/${component}"))`,
    });
  }

  sourceFile.formatText();

  await sourceFile.save();

  project.saveSync();
}
