import { Project } from "ts-morph";
import { join } from "node:path";
import { EMPTY_SET_DEFAULT_DIR } from "@skullmaster/shared";
import { writeFile } from "node:fs/promises";

export function generateRegistry(
  project: Project,
  components: string[],
  isTs: boolean,
) {
  const registryEntries = components
    .map((component) => `"${component}": lazy(() => import("./${component}"))`)
    .join(",\n  ");

  const content = `
  import {
    lazy,
    ${isTs ? "type PropsWithChildren," : ""}
    ${isTs ? "type LazyExoticComponent," : ""}
    ${isTs ? "type ComponentType," : ""}
  } from "react";
  import { Skeleton as SMSkeleton } from "@skullmaster/react";

  const registry${
    isTs
      ? `: Record<
    string,
    LazyExoticComponent<ComponentType<any>>
  >`
      : ""
  } = {
    ${registryEntries}
  };

  ${
    isTs
      ? `
  type SkeletonProps = PropsWithChildren<{
    loading: boolean;
    name: keyof typeof registry;
  }>;
  `
      : ""
  }

  export default function Skeleton({
    loading,
    name,
    children,
  }${isTs ? ": SkeletonProps" : ""}) {
    if (!loading) {
      return (
        <SMSkeleton name={name}>
          {children}
        </SMSkeleton>
      );
    }

    const Component = registry[name];

    if (!Component) {
      return <>loading...</>;
    }

    return <Component />;
  }
  `;

  const sourceFile = project.createSourceFile(
    join(EMPTY_SET_DEFAULT_DIR, "bones", `registry.${isTs ? "tsx" : "jsx"}`),
    content,
    { overwrite: true },
  );

  sourceFile.formatText();
}

export async function generateInitialRegistry(
  outDir: string,
  projectType: string,
) {
  const isTs = projectType.endsWith("ts");

  const ext = isTs ? "tsx" : "jsx";

  const skeletonPropsType = isTs
    ? `
type SkeletonProps = {
  name: string;
};
`
    : "";

  await writeFile(
    `${outDir}/registry.${ext}`,
    `
/* eslint-disable */
/* oxlint-disable */
/* biome-ignore-all lint */
/* @ts-nocheck */

 /**
 * Auto-generated by Skullmaster.
 *
 * Do not edit this file manually.
 * Use Skullmaster commands to add, update, or remove skeletons.
 *
 * To remove unused skeletons:
 *   pnpm skeleton prune
 */


import DefaultBone from "./DefaultBone";

const registry${isTs ? ": Record<string, any>" : ""} = {};

${skeletonPropsType}

export default function Skeleton({
  name,
}${isTs ? ": SkeletonProps" : ""}) {
  const Component = registry[name];

  if (!Component) {
    return <DefaultBone />;
  }

  return <Component />;
}
`,
    "utf8",
  );
}
