/* eslint-disable */
/* oxlint-disable */
/* biome-ignore-all lint */
/* @ts-nocheck */

/**
 * Auto-generated by Skullmaster.
 *
 * Do not edit this file manually.
 * Use Skullmaster commands to add, update, or remove skeletons.
 *
 * To remove unused skeletons:
 *   pnpm skeleton prune
 */

import DefaultBone from "./skeletons/DefaultBone";

const registry: Record<string, any> = {
  Hero: lazy(() => import("./skeletons/Hero")),
  UserProfileCard: lazy(() => import("./skeletons/UserProfileCard")),
  UI: lazy(() => import("./skeletons/UI")),
  Dashboard: lazy(() => import("./skeletons/Dashboard")),
  ImageCard: lazy(() => import("./skeletons/ImageCard")),
  MountainRange: lazy(() => import("./skeletons/MountainRange")),
  CityLights: lazy(() => import("./skeletons/CityLights")),
  DeepOcean: lazy(() => import("./skeletons/DeepOcean")),
  ForestCanopy: lazy(() => import("./skeletons/ForestCanopy")),
  DesertDunes: lazy(() => import("./skeletons/DesertDunes")),
  NightSky: lazy(() => import("./skeletons/NightSky")),
};

import "@skullmaster/react/style.css";
import { lazy } from "react";

type SkeletonProps = {
  name: string;
};

export default function Skeleton({ name }: SkeletonProps) {
  const Component = registry[name];

  if (!Component) {
    return <DefaultBone />;
  }

  return <Component />;
}
