/* eslint-disable */
/* oxlint-disable */
/* biome-ignore-all lint */
/* @ts-nocheck */

/**
 * Auto-generated by Skullmaster.
 *
 * Do not edit this file manually.
 * Use Skullmaster commands to add, update, or remove skeletons.
 *
 * To remove unused skeletons:
 *   pnpm skeleton prune
 */

import "@skullmaster/react/style.css";
import DefaultBone from "./skeletons/DefaultBone";

const registry = {} as const;

type SkeletonProps = {
  name: keyof typeof registry | (string & {});
};

export default function Skeleton({ name }: SkeletonProps) {
  const Component = registry[name];

  if (!Component) {
    return <DefaultBone />;
  }

  return <Component />;
}
