/* eslint-disable */
/* prettier-ignore-start */

/**
 * Auto-generated by Skullmaster.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Changes may be overwritten on the next generation.
 */
export default function Components() {
  return (
    <section
      className="mt-8 empty-set__skeleton"
      data-skullmaster="Components"
      data-depth="-1"
      role="status"
      aria-live="polite"
      aria-busy="true"
    >
      <h2 data-depth="1" className="mb-4 text-2xl font-black">
        <span className="empty-set__text" data-text-node="true" data-depth="1">
          ██████ ██████████
        </span>
      </h2>
      <div className="grid gap-4 sm:grid-cols-2" data-depth="-1">
        <div data-depth="2" className="border-[3px] border-black bg-white p-4">
          <h3 data-depth="3" className="mb-3 font-black">
            <span className="empty-set__text" data-text-node="true" data-depth="3">
              ███████
            </span>
          </h3>
          <div className="flex flex-wrap gap-2" data-depth="-1">
            <button
              data-depth="0"
              className="border-[3px] border-black bg-black px-3 py-1 font-bold text-white"
              data-skeleton-interactive="true"
              aria-hidden="true"
              tabIndex={-1}
            >
              ███████
            </button>
            <button
              data-depth="0"
              className="border-[3px] border-black bg-white px-3 py-1 font-bold"
              data-skeleton-interactive="true"
              aria-hidden="true"
              tabIndex={-1}
            >
              █████████
            </button>
            <button
              data-depth="0"
              className="border-[3px] border-dashed border-black px-3 py-1 font-bold"
              data-skeleton-interactive="true"
              aria-hidden="true"
              tabIndex={-1}
            >
              ███████
            </button>
            <button
              data-depth="0"
              className="border-[3px] border-black bg-red-600 px-3 py-1 font-bold text-white"
              data-skeleton-interactive="true"
              aria-hidden="true"
              tabIndex={-1}
            >
              ██████
            </button>
            <button
              data-depth="0"
              className="border-[3px] border-black bg-white px-3 py-1 font-bold opacity-50"
              data-skeleton-interactive="true"
              aria-hidden="true"
              tabIndex={-1}
            >
              ████████
            </button>
          </div>
        </div>
        <div data-depth="2" className="border-[3px] border-black bg-white p-4">
          <h3 data-depth="3" className="mb-3 font-black">
            <span className="empty-set__text" data-text-node="true" data-depth="3">
              ██████ █ ██████
            </span>
          </h3>
          <div className="mb-4 flex flex-wrap gap-2" data-depth="-1">
            <span
              data-depth="0"
              className="border-2 border-black bg-black px-2 py-0.5 text-xs font-bold text-white"
            >
              ███████
            </span>
            <span
              data-depth="0"
              className="border-2 border-black bg-lime-300 px-2 py-0.5 text-xs font-bold"
            >
              ███████
            </span>
            <span
              data-depth="0"
              className="border-2 border-black bg-yellow-300 px-2 py-0.5 text-xs font-bold"
            >
              ███████
            </span>
            <span
              data-depth="0"
              className="border-2 border-black bg-red-600 px-2 py-0.5 text-xs font-bold text-white"
            >
              ██████
            </span>
          </div>
          <div className="flex flex-col gap-2" data-depth="-1">
            <div
              data-depth="0"
              className="border-2 border-black bg-yellow-300 px-3 py-2 text-sm font-bold"
            >
              ██ █████ ████ ██████
            </div>
            <div
              data-depth="0"
              className="border-2 border-black bg-lime-300 px-3 py-2 text-sm font-bold"
            >
              █ █████████ ██████████
            </div>
          </div>
        </div>
        <div data-depth="2" className="border-[3px] border-black bg-white p-4">
          <h3 data-depth="3" className="mb-3 font-black">
            <span className="empty-set__text" data-text-node="true" data-depth="3">
              ████████
            </span>
          </h3>
          <progress
            data-depth="3"
            className="h-4 w-full border-[3px] border-black [&::-webkit-progress-bar]:bg-white [&::-webkit-progress-value]:bg-lime-400"
          ></progress>
          <p data-depth="3" className="mt-2 text-sm font-bold">
            <span className="empty-set__text" data-text-node="true" data-depth="3">
              ███ ████████
            </span>
          </p>
        </div>
        <div
          data-depth="2"
          data-skullmaster="ImageCard"
          className="overflow-hidden border-[3px] border-black bg-white"
        >
          <img
            data-depth="3"
            className="h-40 w-full object-cover"
            src="data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%22400%22%20height%3D%22300%22%20viewBox%3D%220%200%20400%20300%22%20preserveAspectRatio%3D%22none%22%3E%3Crect%20width%3D%22100%25%22%20height%3D%22100%25%22%20fill%3D%22%23808080%22%2F%3E%3C%2Fsvg%3E"
            data-image-skeleton="true"
          ></img>
          <div className="p-4" data-depth="-1">
            <h3 data-depth="0" className="font-black">
              <span className="empty-set__text" data-text-node="true" data-depth="4">
                █████ ████
              </span>
            </h3>
            <p data-depth="0" className="text-sm text-black/70">
              <span className="empty-set__text" data-text-node="true" data-depth="4">
                █ ████ █████████ █ ████ █████ ████ █████████████ ████████
              </span>
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}

/* prettier-ignore-end */
