/* eslint-disable */
/* prettier-ignore-start */

/**
 * Auto-generated by Skullmaster.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Changes may be overwritten on the next generation.
 */
export default function Hero() {
  return (
    <section
      data-depth="0"
      className="border-[3px] border-black bg-lime-300 p-8 empty-set__skeleton"
      data-skullmaster="Hero"
      role="status"
      aria-live="polite"
      aria-busy="true"
    >
      <div data-depth="1" className="flex flex-col gap-2">
        <h1 data-depth="2" className="text-5xl font-black tracking-tight">
          <span className="empty-set__text" data-text-node="true" data-depth="2">
            ███████████
          </span>
        </h1>
        <p data-depth="2" className="text-xl font-bold">
          <span className="empty-set__text" data-text-node="true" data-depth="2">
            ███████ █ ████████ ███
          </span>
        </p>
        <p data-depth="2" className="max-w-xl text-black/80">
          <span className="empty-set__text" data-text-node="true" data-depth="2">
            █ ██████████ ██ ██████ ███ ██████████ ██████████ ████ █████ ████████████ ███████
          </span>
        </p>
        <div data-depth="2" className="mt-4 flex flex-wrap gap-3">
          <button
            data-depth="3"
            className="border-[3px] border-black bg-black px-4 py-2 font-bold text-white shadow-[4px_4px_0_#000] transition active:translate-x-[2px] active:translate-y-[2px]"
            data-skeleton-interactive="true"
            aria-hidden="true"
            tabIndex={-1}
            data-1p-ignore="true"
            data-lpignore="true"
            data-bwignore="true"
            data-protonpass-ignore="true"
            form="none"
          >
            ███ ███████
          </button>
          <button
            data-depth="3"
            className="border-[3px] border-black bg-white px-4 py-2 font-bold text-black shadow-[4px_4px_0_#000] transition active:translate-x-[2px] active:translate-y-[2px]"
            data-skeleton-interactive="true"
            aria-hidden="true"
            tabIndex={-1}
            data-1p-ignore="true"
            data-lpignore="true"
            data-bwignore="true"
            data-protonpass-ignore="true"
            form="none"
          >
            █████ ████
          </button>
        </div>
      </div>
    </section>
  );
}

/* prettier-ignore-end */
