/* eslint-disable */
/* prettier-ignore-start */

/**
 * Auto-generated by Skullmaster.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Changes may be overwritten on the next generation.
 */
export default function ImageCard() {
  return (
    <div
      data-depth="0"
      className="overflow-hidden border-[3px] border-black bg-white empty-set__skeleton"
      data-skullmaster="ImageCard"
      role="status"
      aria-live="polite"
      aria-busy="true"
    >
      <img
        data-depth="1"
        className="h-40 w-full object-cover"
        src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg'/%3E"
        data-image-skeleton="true"
        alt=""
      />
      <div className="p-4" data-depth="-1">
        <h3 data-depth="2" className="font-black">
          <span className="empty-set__text" data-text-node="true" data-depth="2">
            █████ ████
          </span>
        </h3>
        <p data-depth="2" className="text-sm">
          <span className="empty-set__text" data-text-node="true" data-depth="2">
            █ ████ █████████ █ █████ ██████ ██████████ ██████████
          </span>
        </p>
      </div>
    </div>
  );
}

/* prettier-ignore-end */
