/* eslint-disable */
/* prettier-ignore-start */

/**
 * Auto-generated by Skullmaster.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Changes may be overwritten on the next generation.
 */
export default function MountainRange() {
  return (
    <div
      data-depth="0"
      className="overflow-hidden border-[3px] border-black bg-white empty-set__skeleton"
      data-skullmaster="MountainRange"
      role="status"
      aria-live="polite"
      aria-busy="true"
    >
      <img
        data-depth="1"
        className="h-48 w-full object-cover"
        src="data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%22600%22%20height%3D%22400%22%20viewBox%3D%220%200%20600%20400%22%20preserveAspectRatio%3D%22none%22%3E%3Crect%20width%3D%22100%25%22%20height%3D%22100%25%22%20fill%3D%22%23808080%22%2F%3E%3C%2Fsvg%3E"
        data-image-skeleton="true"
      ></img>
      <div className="p-4" data-depth="-1">
        <h3 data-depth="2" className="font-black">
          <span className="empty-set__text" data-text-node="true" data-depth="2">
            ████████ █████
          </span>
        </h3>
      </div>
    </div>
  );
}

/* prettier-ignore-end */
