/* eslint-disable */
/* prettier-ignore-start */

/**
 * Auto-generated by Skullmaster.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Changes may be overwritten on the next generation.
 */
export default function AnchorLinks() {
  return (
    <div
      data-depth="0"
      className="card interactive-card empty-set__skeleton"
      data-skullmaster="AnchorLinks"
      role="status"
      aria-live="polite"
      aria-busy="true"
    >
      <h3 data-depth="1">
        <span className="empty-set__text" data-text-node="true" data-depth="1">
          ██████ █████
        </span>
      </h3>
      <div className="interactive-demo" data-depth="-1">
        <a
          data-depth="2"
          className="btn btn-ghost"
          data-skeleton-interactive="true"
          aria-hidden="true"
          tabIndex={-1}
        >
          ███████ ████
        </a>
        <a
          data-depth="2"
          className="btn btn-primary"
          data-skeleton-interactive="true"
          aria-hidden="true"
          tabIndex={-1}
        >
          ██████ ████
        </a>
        <a
          data-depth="2"
          className="interactive-link"
          data-skeleton-interactive="true"
          aria-hidden="true"
          tabIndex={-1}
        >
          ████ ████
        </a>
      </div>
    </div>
  );
}

/* prettier-ignore-end */
