/* eslint-disable */
/* prettier-ignore-start */

/**
 * Auto-generated by Skullmaster.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Changes may be overwritten on the next generation.
 */
export default function Buttons() {
  return (
    <div
      data-depth="0"
      className="card interactive-card empty-set__skeleton"
      data-skullmaster="Buttons"
      role="status"
      aria-live="polite"
      aria-busy="true"
    >
      <h3
        data-depth="1"
        data-skull-btlr="0"
        data-skull-btrr="0"
        data-skull-bbrr="0"
        data-skull-bblr="0"
        data-visual-significance="0.24"
      >
        <span className="empty-set__text" data-text-node="true" data-depth="1">
          ███████
        </span>
      </h3>
      <div
        className="interactive-demo"
        data-skull-btlr="0"
        data-skull-btrr="0"
        data-skull-bbrr="0"
        data-skull-bblr="0"
        data-visual-significance="0.00"
        data-depth="-1"
      >
        <button
          data-depth="2"
          className="btn btn-primary"
          data-skull-btlr="0"
          data-skull-btrr="0"
          data-skull-bbrr="0"
          data-skull-bblr="0"
          data-visual-significance="0.70"
          data-skeleton-interactive="true"
          aria-hidden="true"
          tabIndex={-1}
        >
          ██████
        </button>
        <button
          data-depth="2"
          className="btn btn-secondary"
          data-skull-btlr="0"
          data-skull-btrr="0"
          data-skull-bbrr="0"
          data-skull-bblr="0"
          data-visual-significance="0.16"
          data-skeleton-interactive="true"
          aria-hidden="true"
          tabIndex={-1}
        >
          ████████
        </button>
        <button
          data-depth="2"
          className="btn btn-outline"
          data-skull-btlr="0"
          data-skull-btrr="0"
          data-skull-bbrr="0"
          data-skull-bblr="0"
          data-visual-significance="0.45"
          data-skeleton-interactive="true"
          aria-hidden="true"
          tabIndex={-1}
        >
          ███████
        </button>
      </div>
    </div>
  );
}

/* prettier-ignore-end */
