/* eslint-disable */
/* prettier-ignore-start */

/**
 * Auto-generated by Skullmaster.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Changes may be overwritten on the next generation.
 */
export default function DetailsSummary() {
  return (
    <div
      data-depth="0"
      className="card interactive-card empty-set__skeleton"
      data-skullmaster="DetailsSummary"
      role="status"
      aria-live="polite"
      aria-busy="true"
    >
      <h3 data-depth="1">
        <span className="empty-set__text" data-text-node="true" data-depth="1">
          ███████ █ ███████
        </span>
      </h3>
      <details
        data-depth="1"
        className="interactive-details"
        data-skeleton-interactive="true"
        aria-hidden="true"
        tabIndex={-1}
      >
        <summary
          data-depth="2"
          className="interactive-summary"
          data-skeleton-interactive="true"
          aria-hidden="true"
          tabIndex={-1}
        >
          █████ ██ ██████
        </summary>
        <div className="interactive-details-body" data-depth="-1">
          <p data-depth="3">
            <span className="empty-set__text" data-text-node="true" data-depth="3">
              ████ ███████ ██ ███████ ███ ███ ██████ █████████ ████████
            </span>
          </p>
          <p data-depth="3">
            <span className="empty-set__text" data-text-node="true" data-depth="3">
              ██ ██████████ ████████ ███ ███ █████ ██████ █████████
            </span>
          </p>
        </div>
      </details>
    </div>
  );
}

/* prettier-ignore-end */
