/* eslint-disable */
/* prettier-ignore-start */

/**
 * Auto-generated by Skullmaster.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Changes may be overwritten on the next generation.
 */
export default function Dialog() {
  return (
    <div
      data-depth="0"
      className="card interactive-card empty-set__skeleton"
      data-skullmaster="Dialog"
      role="status"
      aria-live="polite"
      aria-busy="true"
    >
      <h3 data-depth="1">
        <span className="empty-set__text" data-text-node="true" data-depth="1">
          ██████
        </span>
      </h3>
      <div className="interactive-demo" data-depth="-1">
        <button
          data-depth="2"
          className="btn btn-primary"
          data-skeleton-interactive="true"
          aria-hidden="true"
          tabIndex={-1}
        >
          ████ ██████
        </button>
      </div>
      <dialog
        data-depth="1"
        className="interactive-dialog"
        data-skeleton-interactive="true"
        aria-hidden="true"
        tabIndex={-1}
      >
        <div className="interactive-dialog-content" data-depth="-1">
          <h3 data-depth="3">
            <span className="empty-set__text" data-text-node="true" data-depth="3">
              █████ ██████
            </span>
          </h3>
          <p data-depth="3">
            <span className="empty-set__text" data-text-node="true" data-depth="3">
              ████ ██ █ ██████ ████████ ███████ ██████ ████
            </span>
            <code data-depth="4">███████████</code>
            <span className="empty-set__text" data-text-node="true" data-depth="3">
              █
            </span>
          </p>
          <form data-depth="-1">
            <button
              data-depth="4"
              className="btn btn-primary"
              data-skeleton-interactive="true"
              aria-hidden="true"
              tabIndex={-1}
            >
              █████
            </button>
          </form>
        </div>
      </dialog>
    </div>
  );
}

/* prettier-ignore-end */
