/* eslint-disable */
/* prettier-ignore-start */

/**
 * Auto-generated by Skullmaster.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Changes may be overwritten on the next generation.
 */
export default function Dialog() {
  return (
    <div
      data-depth="0"
      className="card interactive-card empty-set__skeleton"
      data-skullmaster="Dialog"
      role="status"
      aria-live="polite"
      aria-busy="true"
    >
      <h3
        data-depth="1"
        data-skull-btlr="0"
        data-skull-btrr="0"
        data-skull-bbrr="0"
        data-skull-bblr="0"
        data-visual-significance="0.24"
      >
        <span className="empty-set__text" data-text-node="true" data-depth="1">
          ██████
        </span>
      </h3>
      <div
        className="interactive-demo"
        data-skull-btlr="0"
        data-skull-btrr="0"
        data-skull-bbrr="0"
        data-skull-bblr="0"
        data-visual-significance="0.00"
        data-depth="-1"
      >
        <button
          data-depth="2"
          className="btn btn-primary"
          data-skull-btlr="0"
          data-skull-btrr="0"
          data-skull-bbrr="0"
          data-skull-bblr="0"
          data-visual-significance="0.70"
          data-skeleton-interactive="true"
          aria-hidden="true"
          tabIndex={-1}
        >
          ████ ██████
        </button>
      </div>
      <dialog
        data-depth="1"
        className="interactive-dialog"
        data-skull-btlr="0"
        data-skull-btrr="0"
        data-skull-bbrr="0"
        data-skull-bblr="0"
        data-visual-significance="0.26"
        data-skeleton-interactive="true"
        aria-hidden="true"
        tabIndex={-1}
      >
        <div
          className="interactive-dialog-content"
          data-skull-btlr="0"
          data-skull-btrr="0"
          data-skull-bbrr="0"
          data-skull-bblr="0"
          data-visual-significance="0.00"
          data-depth="-1"
        >
          <h3
            data-depth="3"
            data-skull-btlr="0"
            data-skull-btrr="0"
            data-skull-bbrr="0"
            data-skull-bblr="0"
            data-visual-significance="0.20"
          >
            <span className="empty-set__text" data-text-node="true" data-depth="3">
              ██████ █████
            </span>
          </h3>
          <p
            data-depth="3"
            data-skull-btlr="0"
            data-skull-btrr="0"
            data-skull-bbrr="0"
            data-skull-bblr="0"
            data-visual-significance="0.20"
          >
            <span className="empty-set__text" data-text-node="true" data-depth="3">
              █ ██████ ████████ ███████ ██████ ████
            </span>
            <code
              data-depth="0"
              data-skull-btlr="0"
              data-skull-btrr="0"
              data-skull-bbrr="0"
              data-skull-bblr="0"
              data-visual-significance="0.36"
            >
              ███████████
            </code>
            <span className="empty-set__text" data-text-node="true" data-depth="3">
              █ █████ ████ ██ ██████ ████ ███████ ███ ███ ████ ████
            </span>
          </p>
          <form
            data-skull-btlr="0"
            data-skull-btrr="0"
            data-skull-bbrr="0"
            data-skull-bblr="0"
            data-visual-significance="0.00"
            data-depth="-1"
          >
            <button
              data-depth="0"
              className="btn btn-primary"
              data-skull-btlr="0"
              data-skull-btrr="0"
              data-skull-bbrr="0"
              data-skull-bblr="0"
              data-visual-significance="0.70"
              data-skeleton-interactive="true"
              aria-hidden="true"
              tabIndex={-1}
            >
              █████
            </button>
          </form>
        </div>
      </dialog>
    </div>
  );
}

/* prettier-ignore-end */
