/* eslint-disable */
/* prettier-ignore-start */

/**
 * Auto-generated by Skullmaster.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Changes may be overwritten on the next generation.
 */
export default function FieldsetForm() {
  return (
    <div
      data-depth="0"
      className="card interactive-card empty-set__skeleton"
      data-skullmaster="FieldsetForm"
      role="status"
      aria-live="polite"
      aria-busy="true"
    >
      <h3 data-depth="1">
        <span className="empty-set__text" data-text-node="true" data-depth="1">
          ████████ █ ████
        </span>
      </h3>
      <form className="interactive-form" data-depth="-1"></form>
    </div>
  );
}

/* prettier-ignore-end */
