/* eslint-disable */
/* prettier-ignore-start */

/**
 * Auto-generated by Skullmaster.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Changes may be overwritten on the next generation.
 */
export default function FileColor() {
  return (
    <div
      data-depth="0"
      className="card interactive-card empty-set__skeleton"
      data-skullmaster="FileColor"
      role="status"
      aria-live="polite"
      aria-busy="true"
    >
      <h3
        data-depth="1"
        data-skull-btlr="0"
        data-skull-btrr="0"
        data-skull-bbrr="0"
        data-skull-bblr="0"
        data-visual-significance="0.24"
      >
        <span className="empty-set__text" data-text-node="true" data-depth="1">
          ████ █ █████
        </span>
      </h3>
      <div
        className="interactive-demo interactive-stack"
        data-skull-btlr="0"
        data-skull-btrr="0"
        data-skull-bbrr="0"
        data-skull-bblr="0"
        data-visual-significance="0.00"
        data-depth="-1"
      >
        <label
          data-depth="2"
          className="interactive-label"
          data-skull-btlr="0"
          data-skull-btrr="0"
          data-skull-bbrr="0"
          data-skull-bblr="0"
          data-visual-significance="0.20"
          data-skeleton-interactive="true"
          aria-hidden="true"
          tabIndex={-1}
        >
          <span className="empty-set__text" data-text-node="true" data-depth="2">
            ████
          </span>
          <input
            data-depth="3"
            className="interactive-file"
            type="file"
            data-skull-btlr="0"
            data-skull-btrr="0"
            data-skull-bbrr="0"
            data-skull-bblr="0"
            data-visual-significance="0.20"
            data-skeleton-interactive="true"
            aria-hidden="true"
            tabIndex={-1}
            autoComplete="off"
            data-1p-ignore="true"
            data-lpignore="true"
            data-bwignore="true"
            data-protonpass-ignore="true"
            form="none"
          ></input>
        </label>
        <label
          data-depth="2"
          className="interactive-label"
          data-skull-btlr="0"
          data-skull-btrr="0"
          data-skull-bbrr="0"
          data-skull-bblr="0"
          data-visual-significance="0.20"
          data-skeleton-interactive="true"
          aria-hidden="true"
          tabIndex={-1}
        >
          <span className="empty-set__text" data-text-node="true" data-depth="2">
            █████
          </span>
          <input
            data-depth="3"
            className="interactive-color"
            type="color"
            data-skull-btlr="0"
            data-skull-btrr="0"
            data-skull-bbrr="0"
            data-skull-bblr="0"
            data-visual-significance="0.36"
            data-skeleton-interactive="true"
            aria-hidden="true"
            tabIndex={-1}
            autoComplete="off"
            data-1p-ignore="true"
            data-lpignore="true"
            data-bwignore="true"
            data-protonpass-ignore="true"
            form="none"
          ></input>
        </label>
        <label
          data-depth="2"
          className="interactive-label"
          data-skull-btlr="0"
          data-skull-btrr="0"
          data-skull-bbrr="0"
          data-skull-bblr="0"
          data-visual-significance="0.20"
          data-skeleton-interactive="true"
          aria-hidden="true"
          tabIndex={-1}
        >
          <span className="empty-set__text" data-text-node="true" data-depth="2">
            ████
          </span>
          <input
            data-depth="3"
            className="interactive-input"
            type="date"
            data-skull-btlr="0"
            data-skull-btrr="0"
            data-skull-bbrr="0"
            data-skull-bblr="0"
            data-visual-significance="0.46"
            data-skeleton-interactive="true"
            aria-hidden="true"
            tabIndex={-1}
            autoComplete="off"
            data-1p-ignore="true"
            data-lpignore="true"
            data-bwignore="true"
            data-protonpass-ignore="true"
            form="none"
          ></input>
        </label>
      </div>
    </div>
  );
}

/* prettier-ignore-end */
