/* eslint-disable */
/* prettier-ignore-start */

/**
 * Auto-generated by Skullmaster.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Changes may be overwritten on the next generation.
 */
export default function ForestCanopy() {
  return (
    <div
      data-depth="0"
      data-skullmaster="ForestCanopy"
      className="card image-card-grid  empty-set__skeleton"
      data-seed="forest"
      data-skeleton-interactive="true"
      aria-hidden="true"
      tabIndex={-1}
      role="status"
      aria-live="polite"
      aria-busy="true"
    >
      <img
        data-depth="1"
        className="image-card-grid-img"
        src="data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%22450%22%20height%3D%22450%22%20viewBox%3D%220%200%20450%20450%22%20preserveAspectRatio%3D%22none%22%3E%3Crect%20width%3D%22100%25%22%20height%3D%22100%25%22%20fill%3D%22%23808080%22%2F%3E%3C%2Fsvg%3E"
        data-image-skeleton="true"
      ></img>
      <div className="image-card-grid-body" data-depth="-1">
        <h3 data-depth="2" className="image-card-grid-title">
          <span className="empty-set__text" data-text-node="true" data-depth="2">
            ██████ ██████
          </span>
        </h3>
        <p data-depth="2" className="image-card-grid-desc">
          <span className="empty-set__text" data-text-node="true" data-depth="2">
            █████ ████████ ██████ ██ ███████ █████████ ██████
          </span>
        </p>
      </div>
      <div className="image-card-grid-footer" data-depth="-1">
        <span data-depth="2">███████ ████████</span>
      </div>
    </div>
  );
}

/* prettier-ignore-end */
