/* eslint-disable */
/* prettier-ignore-start */

/**
 * Auto-generated by Skullmaster.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Changes may be overwritten on the next generation.
 */
export default function Hero() {
  return (
    <section
      data-depth="0"
      className="hero-section empty-set__skeleton"
      data-skullmaster="Hero"
      data-skull-btlr="0"
      data-skull-btrr="0"
      data-skull-bbrr="0"
      data-skull-bblr="0"
      role="status"
      aria-live="polite"
      aria-busy="true"
    >
      <div data-depth="1" className="hero-content">
        <h1 data-depth="2" className="hero-title">
          <span className="empty-set__text" data-text-node="true" data-depth="2">
            ███████████
          </span>
        </h1>
        <p data-depth="2" className="hero-subtitle">
          <span className="empty-set__text" data-text-node="true" data-depth="2">
            ███ █████████ ██ ████████
          </span>
        </p>
        <p data-depth="2" className="hero-desc">
          <span className="empty-set__text" data-text-node="true" data-depth="2">
            █ ██████████ ██ ██████ ███ ██████████ ██████████ ████ █████ ████████████ ███████
          </span>
        </p>
        <div data-depth="2" className="hero-actions">
          <button
            data-depth="3"
            className="btn btn-primary"
            data-skeleton-interactive="true"
            aria-hidden="true"
            tabIndex={-1}
          >
            ███ ███████
          </button>
          <button
            data-depth="3"
            className="btn btn-secondary"
            data-skeleton-interactive="true"
            aria-hidden="true"
            tabIndex={-1}
          >
            █████ ████
          </button>
        </div>
      </div>
    </section>
  );
}

/* prettier-ignore-end */
