/* eslint-disable */
/* prettier-ignore-start */

/**
 * Auto-generated by Skullmaster.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Changes may be overwritten on the next generation.
 */
export default function Hero() {
  return (
    <section
      data-depth="0"
      className="hero-section empty-set__skeleton empty-set__skeleton empty-set__skeleton empty-set__skeleton"
      data-skullmaster="Hero"
      role="status"
      aria-live="polite"
      aria-busy="true"
      role="status"
      aria-live="polite"
      aria-busy="true"
    >
      <div className="hero-content" data-depth="-1">
        <h1 data-depth="2" className="hero-title">
          <span className="empty-set__text" data-text-node="true" data-depth="2">
            84jQ76PbHUY
          </span>
        </h1>
        <p data-depth="2" className="hero-subtitle">
          <span className="empty-set__text" data-text-node="true" data-depth="2">
            hrB 0fxYkaQOC -d ~QF9JAK~
          </span>
        </p>
        <p data-depth="2" className="hero-desc">
          <span className="empty-set__text" data-text-node="true" data-depth="2">
            m eTTUb~gh2r Dh i2qVF3 EWM -A~Ne9sjLF .Me-DfbP0f P-mi AWqdD MTRfxK3LzrIR DW_obwA
          </span>
        </p>
        <div className="hero-actions" data-depth="-1">
          <button
            data-depth="3"
            className="btn btn-primary"
            data-skeleton-interactive="true"
            aria-hidden="true"
            tabIndex={-1}
          >
            CcH hyMROlH
          </button>
          <button
            data-depth="3"
            className="btn btn-secondary"
            data-skeleton-interactive="true"
            aria-hidden="true"
            tabIndex={-1}
          >
            UxIRp 5V1U
          </button>
        </div>
      </div>
    </section>
  );
}

/* prettier-ignore-end */
