/* eslint-disable */
/* prettier-ignore-start */

/**
 * Auto-generated by Skullmaster.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Changes may be overwritten on the next generation.
 */
export default function ProgressMeter() {
  return (
    <div
      data-depth="0"
      className="card interactive-card empty-set__skeleton"
      data-skullmaster="ProgressMeter"
      role="status"
      aria-live="polite"
      aria-busy="true"
    >
      <h3 data-depth="1">
        <span className="empty-set__text" data-text-node="true" data-depth="1">
          ████████ █ █████
        </span>
      </h3>
      <div className="interactive-demo interactive-stack" data-depth="-1">
        <label
          data-depth="2"
          className="interactive-label"
          data-skeleton-interactive="true"
          aria-hidden="true"
          tabIndex={-1}
        >
          <span className="empty-set__text" data-text-node="true" data-depth="2">
            ████████ █████
          </span>
          <progress data-depth="3" className="interactive-progress"></progress>
        </label>
        <label
          data-depth="2"
          className="interactive-label"
          data-skeleton-interactive="true"
          aria-hidden="true"
          tabIndex={-1}
        >
          <span className="empty-set__text" data-text-node="true" data-depth="2">
            █████ █████
          </span>
          <meter data-depth="3" className="interactive-meter"></meter>
        </label>
      </div>
    </div>
  );
}

/* prettier-ignore-end */
