/* eslint-disable */
/* prettier-ignore-start */

/**
 * Auto-generated by Skullmaster.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Changes may be overwritten on the next generation.
 */
export default function SelectMenu() {
  return (
    <div
      data-depth="0"
      className="card interactive-card empty-set__skeleton"
      data-skullmaster="SelectMenu"
      role="status"
      aria-live="polite"
      aria-busy="true"
    >
      <h3 data-depth="1">
        <span className="empty-set__text" data-text-node="true" data-depth="1">
          ██████ █ ████████
        </span>
      </h3>
      <div className="interactive-demo interactive-stack" data-depth="-1">
        <label
          data-depth="2"
          className="interactive-label"
          data-skeleton-interactive="true"
          aria-hidden="true"
          tabIndex={-1}
        >
          <span className="empty-set__text" data-text-node="true" data-depth="2">
            ██████
          </span>
          <select
            data-depth="3"
            className="interactive-select"
            data-skeleton-interactive="true"
            aria-hidden="true"
            tabIndex={-1}
          >
            <optgroup
              data-depth="4"
              data-skeleton-interactive="true"
              aria-hidden="true"
              tabIndex={-1}
            >
              <option
                data-depth="5"
                data-skeleton-interactive="true"
                aria-hidden="true"
                tabIndex={-1}
              >
                ██████ ███
              </option>
              <option
                data-depth="5"
                data-skeleton-interactive="true"
                aria-hidden="true"
                tabIndex={-1}
              >
                ██████ ███
              </option>
            </optgroup>
            <optgroup
              data-depth="4"
              data-skeleton-interactive="true"
              aria-hidden="true"
              tabIndex={-1}
            >
              <option
                data-depth="5"
                data-skeleton-interactive="true"
                aria-hidden="true"
                tabIndex={-1}
              >
                ██████ █████
              </option>
              <option
                data-depth="5"
                data-skeleton-interactive="true"
                aria-hidden="true"
                tabIndex={-1}
              >
                ██████ ████
              </option>
            </optgroup>
          </select>
        </label>
        <label
          data-depth="2"
          className="interactive-label"
          data-skeleton-interactive="true"
          aria-hidden="true"
          tabIndex={-1}
        >
          <span className="empty-set__text" data-text-node="true" data-depth="2">
            ████████
          </span>
          <input
            data-depth="3"
            className="interactive-input"
            data-skeleton-interactive="true"
            aria-hidden="true"
            tabIndex={-1}
          ></input>
          <datalist
            data-depth="3"
            data-skeleton-interactive="true"
            aria-hidden="true"
            tabIndex={-1}
          >
            <option
              data-depth="4"
              data-skeleton-interactive="true"
              aria-hidden="true"
              tabIndex={-1}
            ></option>
            <option
              data-depth="4"
              data-skeleton-interactive="true"
              aria-hidden="true"
              tabIndex={-1}
            ></option>
            <option
              data-depth="4"
              data-skeleton-interactive="true"
              aria-hidden="true"
              tabIndex={-1}
            ></option>
            <option
              data-depth="4"
              data-skeleton-interactive="true"
              aria-hidden="true"
              tabIndex={-1}
            ></option>
          </datalist>
        </label>
      </div>
    </div>
  );
}

/* prettier-ignore-end */
