/* eslint-disable */
/* prettier-ignore-start */

/**
 * Auto-generated by Skullmaster.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Changes may be overwritten on the next generation.
 */
export default function Textarea() {
  return (
    <div
      data-depth="0"
      className="card interactive-card empty-set__skeleton"
      data-skullmaster="Textarea"
      role="status"
      aria-live="polite"
      aria-busy="true"
    >
      <h3
        data-depth="1"
        data-skull-btlr="0"
        data-skull-btrr="0"
        data-skull-bbrr="0"
        data-skull-bblr="0"
        data-visual-significance="0.24"
      >
        <span className="empty-set__text" data-text-node="true" data-depth="1">
          ████████
        </span>
      </h3>
      <div
        className="interactive-demo interactive-stack"
        data-skull-btlr="0"
        data-skull-btrr="0"
        data-skull-bbrr="0"
        data-skull-bblr="0"
        data-visual-significance="0.00"
        data-depth="-1"
      >
        <textarea
          data-depth="2"
          className="interactive-textarea"
          data-skull-btlr="0"
          data-skull-btrr="0"
          data-skull-bbrr="0"
          data-skull-bblr="0"
          data-visual-significance="0.46"
          data-skeleton-interactive="true"
          aria-hidden="true"
          tabIndex={-1}
          autoComplete="off"
          data-1p-ignore="true"
          data-lpignore="true"
          data-bwignore="true"
          data-protonpass-ignore="true"
          form="none"
        >
          ████ ████████ ████████ █████
        </textarea>
      </div>
    </div>
  );
}

/* prettier-ignore-end */
