/* eslint-disable */
/* prettier-ignore-start */

/**
 * Auto-generated by Skullmaster.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Changes may be overwritten on the next generation.
 */
export default function Textarea() {
  return (
    <div
      data-depth="0"
      className="card interactive-card empty-set__skeleton"
      data-skullmaster="Textarea"
      role="status"
      aria-live="polite"
      aria-busy="true"
    >
      <h3 data-depth="1">
        <span className="empty-set__text" data-text-node="true" data-depth="1">
          ████████
        </span>
      </h3>
      <div className="interactive-demo interactive-stack" data-depth="-1">
        <textarea
          data-depth="2"
          className="interactive-textarea"
          data-skeleton-interactive="true"
          aria-hidden="true"
          tabIndex={-1}
        >
          ████ ████████ ████████ █████
        </textarea>
      </div>
    </div>
  );
}

/* prettier-ignore-end */
