/* eslint-disable */
/* prettier-ignore-start */

/**
 * Auto-generated by Skullmaster.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Changes may be overwritten on the next generation.
 */
export default function TextInputs() {
  return (
    <div
      data-depth="0"
      className="card interactive-card empty-set__skeleton"
      data-skullmaster="TextInputs"
      role="status"
      aria-live="polite"
      aria-busy="true"
    >
      <h3 data-depth="1">
        <span className="empty-set__text" data-text-node="true" data-depth="1">
          ████ ██████
        </span>
      </h3>
      <div className="interactive-demo interactive-stack" data-depth="-1">
        <label
          data-depth="2"
          className="interactive-label"
          data-skeleton-interactive="true"
          aria-hidden="true"
          tabIndex={-1}
        >
          <span className="empty-set__text" data-text-node="true" data-depth="2">
            ████
          </span>
          <input
            data-depth="3"
            className="interactive-input"
            type="text"
            data-skeleton-interactive="true"
            aria-hidden="true"
            tabIndex={-1}
          ></input>
        </label>
        <label
          data-depth="2"
          className="interactive-label"
          data-skeleton-interactive="true"
          aria-hidden="true"
          tabIndex={-1}
        >
          <span className="empty-set__text" data-text-node="true" data-depth="2">
            ██████
          </span>
          <input
            data-depth="3"
            className="interactive-input"
            type="search"
            data-skeleton-interactive="true"
            aria-hidden="true"
            tabIndex={-1}
          ></input>
        </label>
        <label
          data-depth="2"
          className="interactive-label"
          data-skeleton-interactive="true"
          aria-hidden="true"
          tabIndex={-1}
        >
          <span className="empty-set__text" data-text-node="true" data-depth="2">
            ███
          </span>
          <input
            data-depth="3"
            className="interactive-input"
            type="url"
            data-skeleton-interactive="true"
            aria-hidden="true"
            tabIndex={-1}
          ></input>
        </label>
        <label
          data-depth="2"
          className="interactive-label"
          data-skeleton-interactive="true"
          aria-hidden="true"
          tabIndex={-1}
        >
          <span className="empty-set__text" data-text-node="true" data-depth="2">
            ███
          </span>
          <input
            data-depth="3"
            className="interactive-input"
            type="tel"
            data-skeleton-interactive="true"
            aria-hidden="true"
            tabIndex={-1}
          ></input>
        </label>
        <label
          data-depth="2"
          className="interactive-label"
          data-skeleton-interactive="true"
          aria-hidden="true"
          tabIndex={-1}
        >
          <span className="empty-set__text" data-text-node="true" data-depth="2">
            █████
          </span>
          <input
            data-depth="3"
            className="interactive-input"
            type="email"
            data-skeleton-interactive="true"
            aria-hidden="true"
            tabIndex={-1}
          ></input>
        </label>
        <label
          data-depth="2"
          className="interactive-label"
          data-skeleton-interactive="true"
          aria-hidden="true"
          tabIndex={-1}
        >
          <span className="empty-set__text" data-text-node="true" data-depth="2">
            ██████
          </span>
          <input
            data-depth="3"
            className="interactive-input"
            type="number"
            data-skeleton-interactive="true"
            aria-hidden="true"
            tabIndex={-1}
          ></input>
        </label>
        <label
          data-depth="2"
          className="interactive-label"
          data-skeleton-interactive="true"
          aria-hidden="true"
          tabIndex={-1}
        >
          <span className="empty-set__text" data-text-node="true" data-depth="2">
            ████████
          </span>
          <input
            data-depth="3"
            className="interactive-input"
            type="password"
            data-skeleton-interactive="true"
            aria-hidden="true"
            tabIndex={-1}
          ></input>
        </label>
      </div>
    </div>
  );
}

/* prettier-ignore-end */
