/* eslint-disable */
/* prettier-ignore-start */

/**
 * Auto-generated by Skullmaster.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Changes may be overwritten on the next generation.
 */
export default function UserProfileCard() {
  return (
    <div
      data-depth="0"
      className="card profile-card empty-set__skeleton"
      data-skullmaster="UserProfileCard"
      role="status"
      aria-live="polite"
      aria-busy="true"
    >
      <div data-depth="1" className="profile-avatar"></div>
      <h2 data-depth="1" className="profile-name">
        <span className="empty-set__text" data-text-node="true" data-depth="1">
          ████ ███
        </span>
      </h2>
      <span data-depth="1" className="profile-role">
        █████████ ████████
      </span>
      <p data-depth="1" className="profile-bio">
        <span className="empty-set__text" data-text-node="true" data-depth="1">
          ████████ █████████ ███████ ███ ███████████ █████████ ██████████ ██████ ███ █████████████
        </span>
      </p>
      <div className="profile-stats" data-depth="-1">
        <div className="stat" data-depth="-1">
          <strong data-depth="3">████</strong>
          <span data-depth="3">█████████</span>
        </div>
        <div className="stat" data-depth="-1">
          <strong data-depth="3">███</strong>
          <span data-depth="3">█████████</span>
        </div>
        <div className="stat" data-depth="-1">
          <strong data-depth="3">██</strong>
          <span data-depth="3">████████</span>
        </div>
      </div>
      <button
        data-depth="1"
        className="btn btn-primary btn-full"
        data-skeleton-interactive="true"
        aria-hidden="true"
        tabIndex={-1}
      >
        ██████
      </button>
    </div>
  );
}

/* prettier-ignore-end */
