export default function Projects() {
    return (<section className="py-32 empty-set__skeleton" data-depth="-1" role="status" aria-live="polite" aria-busy="true"><div className="container" data-depth="-1"><h1 data-depth="2" className="text-7xl leading-tight uppercase"></h1><div className="mt-10 grid grid-cols-1 gap-6 md:grid-cols-2" data-depth="-1"><div data-depth="3" className="group overflow-hidden rounded-lg border border-border bg-background" style={{
            opacity: "0",
            transform: "translateY(50px)"
          }}><a data-depth="4" className="block overflow-hidden"><img data-depth="5" className="h-96 w-full object-cover transition-transform duration-500 ease-in-out group-hover:scale-105" src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg'/%3E" data-image-skeleton="true"></img></a><div className="flex items-center justify-between px-5 py-4" data-depth="-1"><div data-depth="-1"><h2 data-depth="6" className="text-lg font-semibold"></h2><p data-depth="6" className="text-muted-foreground"><span className="empty-set__text" data-text-node="true" data-depth="6">Architecture</span></p></div><div data-depth="5" className="rounded-2xl border border-border px-5 py-2 text-sm font-semibold"></div></div></div><div data-depth="3" className="group overflow-hidden rounded-lg border border-border bg-background" style={{
            opacity: "0",
            transform: "translateY(50px)"
          }}><a data-depth="4" className="block overflow-hidden"><img data-depth="5" className="h-96 w-full object-cover transition-transform duration-500 ease-in-out group-hover:scale-105" src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg'/%3E" data-image-skeleton="true"></img></a><div className="flex items-center justify-between px-5 py-4" data-depth="-1"><div data-depth="-1"><h2 data-depth="6" className="text-lg font-semibold"></h2><p data-depth="6" className="text-muted-foreground"><span className="empty-set__text" data-text-node="true" data-depth="6">Urban Design</span></p></div><div data-depth="5" className="rounded-2xl border border-border px-5 py-2 text-sm font-semibold"></div></div></div><div data-depth="3" className="group overflow-hidden rounded-lg border border-border bg-background" style={{
            opacity: "0",
            transform: "translateY(50px)"
          }}><a data-depth="4" className="block overflow-hidden"><img data-depth="5" className="h-96 w-full object-cover transition-transform duration-500 ease-in-out group-hover:scale-105" src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg'/%3E" data-image-skeleton="true"></img></a><div className="flex items-center justify-between px-5 py-4" data-depth="-1"><div data-depth="-1"><h2 data-depth="6" className="text-lg font-semibold"></h2><p data-depth="6" className="text-muted-foreground"><span className="empty-set__text" data-text-node="true" data-depth="6">Interior</span></p></div><div data-depth="5" className="rounded-2xl border border-border px-5 py-2 text-sm font-semibold"></div></div></div><div data-depth="3" className="group overflow-hidden rounded-lg border border-border bg-background" style={{
            opacity: "0",
            transform: "translateY(50px)"
          }}><a data-depth="4" className="block overflow-hidden"><img data-depth="5" className="h-96 w-full object-cover transition-transform duration-500 ease-in-out group-hover:scale-105" src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg'/%3E" data-image-skeleton="true"></img></a><div className="flex items-center justify-between px-5 py-4" data-depth="-1"><div data-depth="-1"><h2 data-depth="6" className="text-lg font-semibold"></h2><p data-depth="6" className="text-muted-foreground"><span className="empty-set__text" data-text-node="true" data-depth="6">Product Design</span></p></div><div data-depth="5" className="rounded-2xl border border-border px-5 py-2 text-sm font-semibold"></div></div></div><div data-depth="3" className="group overflow-hidden rounded-lg border border-border bg-background" style={{
            opacity: "0",
            transform: "translateY(50px)"
          }}><a data-depth="4" className="block overflow-hidden"><img data-depth="5" className="h-96 w-full object-cover transition-transform duration-500 ease-in-out group-hover:scale-105" src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg'/%3E" data-image-skeleton="true"></img></a><div className="flex items-center justify-between px-5 py-4" data-depth="-1"><div data-depth="-1"><h2 data-depth="6" className="text-lg font-semibold"></h2><p data-depth="6" className="text-muted-foreground"><span className="empty-set__text" data-text-node="true" data-depth="6">Residential</span></p></div><div data-depth="5" className="rounded-2xl border border-border px-5 py-2 text-sm font-semibold"></div></div></div><div data-depth="3" className="group overflow-hidden rounded-lg border border-border bg-background" style={{
            opacity: "0",
            transform: "translateY(50px)"
          }}><a data-depth="4" className="block overflow-hidden"><img data-depth="5" className="h-96 w-full object-cover transition-transform duration-500 ease-in-out group-hover:scale-105" src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg'/%3E" data-image-skeleton="true"></img></a><div className="flex items-center justify-between px-5 py-4" data-depth="-1"><div data-depth="-1"><h2 data-depth="6" className="text-lg font-semibold"></h2><p data-depth="6" className="text-muted-foreground"><span className="empty-set__text" data-text-node="true" data-depth="6">Sustainable Design</span></p></div><div data-depth="5" className="rounded-2xl border border-border px-5 py-2 text-sm font-semibold"></div></div></div></div></div></section>);
}
