/* eslint-disable */
/* prettier-ignore-start */

/**
 * Auto-generated by Skullmaster.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Changes may be overwritten on the next generation.
 */
export default function Contact7() {
  return (
    <section
      data-depth="0"
      className="empty-set__skeleton py-32"
      data-skullmaster="Contact7"
      role="status"
      aria-live="polite"
      aria-busy="true"
    >
      <div className="container" data-depth="-1">
        <div className="mx-auto max-w-6xl" data-depth="-1">
          <div className="mb-14" data-depth="-1">
            <h1
              data-depth="4"
              className="mb-4 text-4xl font-medium tracking-tight md:text-5xl"
            >
              <span
                className="empty-set__text"
                data-text-node="true"
                data-depth="4"
              >
                KQS_mnN Zd
              </span>
            </h1>
            <p data-depth="4" className="text-muted-foreground">
              <span
                className="empty-set__text"
                data-text-node="true"
                data-depth="4"
              >
                RRLv 2 Jt6dr8GC xY p6V4 Wn2HfbzV90c fr_CG b3s A6UbEAq sd- i- uG_
                31u--l71 kRUmuh
              </span>
            </p>
          </div>
          <div className="grid gap-6 md:grid-cols-2" data-depth="-1">
            <div data-depth="4" className="rounded-xl bg-muted/50 p-8">
              <svg
                data-depth="5"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
                className="lucide lucide-mail mb-4 size-5 text-muted-foreground"
                aria-hidden="true"
              ></svg>
              <p data-depth="5" className="mb-1 font-medium">
                <span
                  className="empty-set__text"
                  data-text-node="true"
                  data-depth="5"
                >
                  T3y~8
                </span>
              </p>
              <p data-depth="5" className="mb-4 text-sm text-muted-foreground">
                <span
                  className="empty-set__text"
                  data-text-node="true"
                  data-depth="5"
                >
                  bj 9swsBd_ 9n Ckj y3J9CK LRWIr8 aF _.KmUu
                </span>
              </p>
              <a
                data-depth="5"
                className="hover:underline"
                data-skeleton-interactive="true"
                aria-hidden="true"
                tabIndex={-1}
              >
                4Xtd3iva4mzBCIP6w
              </a>
            </div>
            <div data-depth="4" className="rounded-xl bg-muted/50 p-8">
              <svg
                data-depth="5"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
                className="lucide lucide-map-pin mb-4 size-5 text-muted-foreground"
                aria-hidden="true"
              ></svg>
              <p data-depth="5" className="mb-1 font-medium">
                <span
                  className="empty-set__text"
                  data-text-node="true"
                  data-depth="5"
                >
                  owjahR
                </span>
              </p>
              <p data-depth="5" className="mb-4 text-sm text-muted-foreground">
                <span
                  className="empty-set__text"
                  data-text-node="true"
                  data-depth="5"
                >
                  c3Xr C9 e_Q hBEXRl SZK C t79U_
                </span>
              </p>
              <a
                data-depth="5"
                className="hover:underline"
                data-skeleton-interactive="true"
                aria-hidden="true"
                tabIndex={-1}
              >
                A 2ii-d Loi -tbDifObT Mp2A JHG3
              </a>
            </div>
            <div data-depth="4" className="rounded-xl bg-muted/50 p-8">
              <svg
                data-depth="5"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
                className="lucide lucide-phone mb-4 size-5 text-muted-foreground"
                aria-hidden="true"
              ></svg>
              <p data-depth="5" className="mb-1 font-medium">
                <span
                  className="empty-set__text"
                  data-text-node="true"
                  data-depth="5"
                >
                  _KS-R
                </span>
              </p>
              <p data-depth="5" className="mb-4 text-sm text-muted-foreground">
                <span
                  className="empty-set__text"
                  data-text-node="true"
                  data-depth="5"
                >
                  G7ml6 cKCmsrXdc 6agrxk2y E4tjyqep
                </span>
              </p>
              <a
                data-depth="5"
                className="hover:underline"
                data-skeleton-interactive="true"
                aria-hidden="true"
                tabIndex={-1}
              >
                a1lvt xaDZAJm-
              </a>
            </div>
            <div data-depth="4" className="rounded-xl bg-muted/50 p-8">
              <svg
                data-depth="5"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
                className="lucide lucide-message-circle mb-4 size-5 text-muted-foreground"
                aria-hidden="true"
              ></svg>
              <p data-depth="5" className="mb-1 font-medium">
                <span
                  className="empty-set__text"
                  data-text-node="true"
                  data-depth="5"
                >
                  E_36 0UFD
                </span>
              </p>
              <p data-depth="5" className="mb-4 text-sm text-muted-foreground">
                <span
                  className="empty-set__text"
                  data-text-node="true"
                  data-depth="5"
                >
                  zFx KZN~ZbO ~jb9 lxzu Wzj XeXrv21 46uyw
                </span>
              </p>
              <a
                data-depth="5"
                className="hover:underline"
                data-skeleton-interactive="true"
                aria-hidden="true"
                tabIndex={-1}
              >
                2muY4 49Vq
              </a>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}

/* prettier-ignore-end */
