/* eslint-disable */
/* prettier-ignore-start */

/**
 * Auto-generated by Skullmaster.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Changes may be overwritten on the next generation.
 */
export default function Testimonial10() {
  return (
    <section
      data-depth="0"
      className="py-32 empty-set__skeleton"
      data-skullmaster="Testimonial10"
      role="status"
      aria-live="polite"
      aria-busy="true"
    >
      <div className="container" data-depth="-1">
        <div className="flex flex-col items-center text-center" data-depth="-1">
          <p data-depth="3" className="mb-16 max-w-4xl px-8 font-medium lg:text-3xl">
            <span className="empty-set__text" data-text-node="true" data-depth="3">
              6zVouT 2S4Xo s3_FS 1mZ lSF3 IA49XICp8_R morBjz76I9Z 2VfZV u.E5 scOOYuOxGj HdOdyT7t
              BP~pLI wk_8Pi hroNU b34~-GK TEQ ymz9G cFiYlQ9MSX_6 IDLp~waj7Uj
            </span>
          </p>
          <div className="flex items-center gap-2 md:gap-4" data-depth="-1">
            <span
              data-depth="4"
              data-slot="avatar"
              data-size="default"
              className="group/avatar relative flex shrink-0 rounded-full select-none after:absolute after:inset-0 after:rounded-full after:border after:border-border after:mix-blend-darken data-[size=lg]:size-10 data-[size=sm]:size-6 dark:after:mix-blend-lighten size-12 md:size-16"
            >
              <img
                data-depth="5"
                data-slot="avatar-image"
                className="aspect-square size-full rounded-full object-cover"
                data-natural-w="288"
                data-natural-h="288"
                src="data:image/svg+xml,%0A%20%20%20%20%3Csvg%0A%20%20%20%20%20%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%0A%20%20%20%20%20%20width%3D%22288%22%0A%20%20%20%20%20%20height%3D%22288%22%0A%20%20%20%20%20%20viewBox%3D%220%200%20288%20288%22%0A%20%20%20%20%20%20preserveAspectRatio%3D%22none%22%0A%20%20%20%20%3E%0A%20%20%20%20%20%20%3Cdefs%3E%0A%20%20%20%20%20%20%20%20%3ClinearGradient%20id%3D%22shimmer%22%20x1%3D%22-100%25%22%20y1%3D%220%22%20x2%3D%22100%25%22%20y2%3D%220%22%3E%0A%20%20%20%20%20%20%20%20%20%20%3Cstop%20offset%3D%220%25%22%20stop-color%3D%22%23e5e7eb%22%20%2F%3E%0A%20%20%20%20%20%20%20%20%20%20%3Cstop%20offset%3D%2245%25%22%20stop-color%3D%22%23e5e7eb%22%20%2F%3E%0A%20%20%20%20%20%20%20%20%20%20%3Cstop%20offset%3D%2250%25%22%20stop-color%3D%22%23f3f4f6%22%20%2F%3E%0A%20%20%20%20%20%20%20%20%20%20%3Cstop%20offset%3D%2255%25%22%20stop-color%3D%22%23e5e7eb%22%20%2F%3E%0A%20%20%20%20%20%20%20%20%20%20%3Cstop%20offset%3D%22100%25%22%20stop-color%3D%22%23e5e7eb%22%20%2F%3E%0A%0A%20%20%20%20%20%20%20%20%20%20%3CanimateTransform%0A%20%20%20%20%20%20%20%20%20%20%20%20attributeName%3D%22gradientTransform%22%0A%20%20%20%20%20%20%20%20%20%20%20%20type%3D%22translate%22%0A%20%20%20%20%20%20%20%20%20%20%20%20from%3D%22-1%200%22%0A%20%20%20%20%20%20%20%20%20%20%20%20to%3D%221%200%22%0A%20%20%20%20%20%20%20%20%20%20%20%20dur%3D%221.5s%22%0A%20%20%20%20%20%20%20%20%20%20%20%20repeatCount%3D%22indefinite%22%0A%20%20%20%20%20%20%20%20%20%20%2F%3E%0A%20%20%20%20%20%20%20%20%3C%2FlinearGradient%3E%0A%20%20%20%20%20%20%3C%2Fdefs%3E%0A%0A%20%20%20%20%20%20%3Crect%0A%20%20%20%20%20%20%20%20width%3D%22100%25%22%0A%20%20%20%20%20%20%20%20height%3D%22100%25%22%0A%20%20%20%20%20%20%20%20fill%3D%22url(%23shimmer)%22%0A%20%20%20%20%20%20%2F%3E%0A%20%20%20%20%3C%2Fsvg%3E%0A%20%20"
                data-image-skeleton="true"
              ></img>
            </span>
            <div className="text-left" data-depth="-1">
              <p data-depth="5" className="text-sm font-medium md:text-base">
                <span className="empty-set__text" data-text-node="true" data-depth="5">
                  mP11IE2X 3Jgj
                </span>
              </p>
              <p data-depth="5" className="text-sm text-muted-foreground md:text-base">
                <span className="empty-set__text" data-text-node="true" data-depth="5">
                  jQ__
                </span>
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

/* prettier-ignore-end */
